# Generated by Django 4.2.7 on 2023-12-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registerinfo_groups_registerinfo_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registerinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registerinfo',
            name='user_permissions',
        ),
    ]
