# Generated by Django 4.2.7 on 2023-12-06 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_registerinfo_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registerinfo",
            options={"verbose_name": "registerinfo", "verbose_name_plural": "users"},
        ),
    ]
