# Generated by Django 4.2.7 on 2023-12-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_gender_alter_profile_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="licencePhoto",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/userimages"
            ),
        ),
    ]
