# Generated by Django 4.2.7 on 2024-01-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_profile_licencephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerinfo",
            name="block",
            field=models.BooleanField(default=False),
        ),
    ]
