# Generated by Django 4.2.7 on 2024-01-01 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_registerinfo_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registerinfo",
            name="block",
        ),
    ]
