# Generated by Django 4.2.7 on 2024-01-02 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_profile_is_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_block",
        ),
    ]
