# Generated by Django 4.2.7 on 2024-01-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_profile_is_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerinfo",
            name="is_block",
            field=models.BooleanField(default=False),
        ),
    ]
