# Generated by Django 4.2.7 on 2023-12-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cars_options_alter_cars_carimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='carType',
            field=models.CharField(choices=[('SUV', 'SUV'), ('MPV', 'MPV'), ('EV', 'EV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], default='', max_length=20),
        ),
    ]
