# Generated by Django 4.2.7 on 2023-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cars_cartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='carNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cars',
            name='rc_expired_date',
            field=models.CharField(choices=[('SUV', 'SUV'), ('MPV', 'MPV'), ('EV', 'EV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cars',
            name='seatingCapacity',
            field=models.CharField(default='', max_length=20),
        ),
    ]
