# Generated by Django 4.2.7 on 2023-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_pickupdata_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickupdata",
            name="mobile_number",
            field=models.BigIntegerField(),
        ),
    ]
