# Generated by Django 4.2.7 on 2023-12-11 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_pickupdata_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupdata',
            options={'verbose_name': 'PickupData', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AddField(
            model_name='pickupdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
