# Generated by Django 4.2.7 on 2023-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_pickupdata_options_pickupdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdata',
            name='licence_ID',
            field=models.CharField(max_length=50),
        ),
    ]
