# Generated by Django 4.2.7 on 2023-12-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='in_garage',
            field=models.BooleanField(default=True),
        ),
    ]
