# Generated by Django 4.2.7 on 2023-12-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_cars_in_garage"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
