# Generated by Django 4.2.7 on 2023-12-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_cars_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
