# Generated by Django 4.2.7 on 2023-12-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_alter_cars_carnumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="stock",
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.cars"
                    ),
                ),
            ],
        ),
    ]
