# Generated by Django 4.2.7 on 2023-12-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_stock_stock_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupdata',
            options={'verbose_name': 'PickupData', 'verbose_name_plural': 'Bookings Details'},
        ),
        migrations.AddField(
            model_name='pickupdata',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
