# Generated by Django 4.2.7 on 2023-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_pickupdata_bookeddate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamagePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Plan",
                    models.CharField(
                        choices=[
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Diamond", "Diamond"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
