# Generated by Django 4.2.7 on 2023-12-23 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_damagepolicy_details_damagepolicy_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DamagePolicy",
        ),
    ]
