# Generated by Django 4.2.7 on 2023-12-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_alter_pickupdata_picklocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickupdata",
            name="totalAMT",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
