# Generated by Django 4.2.7 on 2024-01-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_alter_payment_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="carType",
            field=models.CharField(
                choices=[
                    ("SUV", "SUV"),
                    ("MPV", "MPV"),
                    ("EV", "EV"),
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                    ("Classic", "Classic"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
